# Generated by Django 6.0.5 on 2026-05-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbingAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('comp_type', models.CharField(choices=[('qualifier', 'Qualifier'), ('finals', 'Finals')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('top_x_advance', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comps', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='climbingAPI.gym')),
                ('linked_qualifier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_finals', to='climbingAPI.competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='climbingAPI.competition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompClimb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_value', models.IntegerField(default=100)),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_entries', to='climbingAPI.climb')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_climbs', to='climbingAPI.competition')),
                ('comp_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climbingAPI.compround')),
            ],
            options={
                'unique_together': {('competition', 'climb')},
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='climbingAPI.competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=1)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('comp_climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_sends', to='climbingAPI.compclimb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_sends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comp_climb', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CompRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='climbingAPI.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_registrations', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climbingAPI.division')),
            ],
            options={
                'unique_together': {('competition', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FinalsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topped', models.BooleanField(default=False)),
                ('top_attempts', models.IntegerField(blank=True, null=True)),
                ('zoned', models.BooleanField(default=False)),
                ('zone_attempts', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('comp_climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_results', to='climbingAPI.compclimb')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judged_results', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comp_climb', 'user')},
            },
        ),
    ]
