# Generated by Django 6.0.5 on 2026-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbingAPI', '0002_competition_compround_compclimb_division_compsend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
