# Generated by Django 6.0.5 on 2026-05-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbingAPI', '0003_user_apple_id_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apple_id',
        ),
    ]
