# Generated by Django 6.0.3 on 2026-06-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbingAPI', '0004_remove_user_apple_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
