# Generated by Django 6.0.3 on 2026-10-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbingAPI', '0007_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
