# Generated by Django 6.0.3 on 2026-10-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbingAPI', '0008_wall_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
